name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.TOKEN }}
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
# name: Waka Readme

# on:
#   workflow_dispatch:
#   schedule:
#     # Runs at 12am UTC
#     - cron: "* * * * *"

# jobs:
#   update-readme:
#     name: WakaReadme DevMetrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
# #           GH_TOKEN: ${{ secrets.TOKEN }}
#           REPOSITORY: HsiangNianian/HsiangNianian
#           SHOW_TITLE: true
#           BLOCKS: ->
#           TIME_RANGE: all_time
#           SHOW_TIME: true
#           SHOW_MASKED_TIME: true
#           LANG_COUNT: 10

